/*
 * Attribute.java	 <br>
 * 2011-12-9<br>
 * com.shinetech.magento <br>
 * Copyright (C), 2011-2012, ShineTech. Co., Ltd.<br>
 * 
 */
package com.shinetech.magento.entity;

/**
 * magento 商城所有属性，每个属性名为：_${entity_type_id}_${attribute_code}=${attribute_code}
 *
 * @author <a href="mailto:wushexin@gmail.com">Frank.Wu</a>
 * @version 1.0.0
 */

public class Attribute {
	public String _1_confirmation="confirmation";
	public String _1_created_at="created_at";
 	public String _1_created_in="created_in";
 	public String _1_default_billing="default_billing";
 	public String _1_default_shipping="default_shipping";
 	public String _1_dob="dob";
 	public String _1_email="email";
 	public String _1_firstname="firstname";
 	public String _1_gender="gender";
 	public String _1_group_id="group_id";
 	public String _1_lastname="lastname";
 	public String _1_middlename="middlename";
 	public String _1_password_hash="password_hash";
 	public String _1_prefix="prefix";
 	public String _1_store_id="store_id";
 	public String _1_suffix="suffix";
 	public String _1_taxvat="taxvat";
 	public String _1_website_id="website_id";
 	public String _2_city="city";
 	public String _2_company="company";
 	public String _2_country_id="country_id";
 	public String _2_fax="fax";
 	public String _2_firstname="firstname";
 	public String _2_lastname="lastname";
 	public String _2_middlename="middlename";
 	public String _2_postcode="postcode";
 	public String _2_prefix="prefix";
 	public String _2_region="region";
 	public String _2_region_id="region_id";
 	public String _2_street="street";
 	public String _2_suffix="suffix";
 	public String _2_telephone="telephone";
 	public String _3_all_children="all_children";
 	public String _3_available_sort_by="available_sort_by";
 	public String _3_children="children";
 	public String _3_children_count="children_count";
 	public String _3_custom_apply_to_products="custom_apply_to_products";
 	public String _3_custom_design="custom_design";
 	public String _3_custom_design_from="custom_design_from";
 	public String _3_custom_design_to="custom_design_to";
 	public String _3_custom_layout_update="custom_layout_update";
 	public String _3_custom_use_parent_settings="custom_use_parent_settings";
 	public String _3_default_sort_by="default_sort_by";
 	public String _3_description="description";
 	public String _3_display_mode="display_mode";
 	public String _3_filter_price_range="filter_price_range";
 	public String _3_image="image";
 	public String _3_include_in_menu="include_in_menu";
 	public String _3_is_active="is_active";
 	public String _3_is_anchor="is_anchor";
 	public String _3_landing_page="landing_page";
 	public String _3_level="level";
 	public String _3_meta_description="meta_description";
 	public String _3_meta_keywords="meta_keywords";
 	public String _3_meta_title="meta_title";
 	public String _3_name="name";
 	public String _3_page_layout="page_layout";
 	public String _3_path="path";
 	public String _3_path_in_store="path_in_store";
 	public String _3_position="position";
 	public String _3_thumbnail="thumbnail";
 	public String _3_url_key="url_key";
 	public String _3_url_path="url_path";
 	public String _4_back_details="back_details";
 	public String _4_body_shape="body_shape";
 	public String _4_category_ids="category_ids";
 	public String _4_country_of_manufacture="country_of_manufacture";
 	public String _4_created_at="created_at";
 	public String _4_custom_design="custom_design";
 	public String _4_custom_design_from="custom_design_from";
 	public String _4_custom_design_to="custom_design_to";
 	public String _4_custom_layout_update="custom_layout_update";
 	public String _4_description="description";
 	public String _4_discount="discount";
 	public String _4_embellishment="embellishment";
 	public String _4_enable_googlecheckout="enable_googlecheckout";
 	public String _4_fabric="fabric";
 	public String _4_gallery="gallery";
 	public String _4_gift_message_available="gift_message_available";
 	public String _4_has_options="has_options";
 	public String _4_hemline="hemline";
 	public String _4_image="image";
 	public String _4_image_label="image_label";
 	public String _4_is_imported="is_imported";
 	public String _4_is_recurring="is_recurring";
 	public String _4_itemcode="itemcode";
 	public String _4_links_exist="links_exist";
 	public String _4_links_purchased_separately="links_purchased_separately";
 	public String _4_links_title="links_title";
 	public String _4_media_gallery="media_gallery";
 	public String _4_meta_description="meta_description";
 	public String _4_meta_keyword="meta_keyword";
 	public String _4_meta_title="meta_title";
 	public String _4_minimal_price="minimal_price";
 	public String _4_msrp="msrp";
 	public String _4_msrp_display_actual_price_type="msrp_display_actual_price_type";
 	public String _4_msrp_enabled="msrp_enabled";
 	public String _4_name="name";
 	public String _4_neckline="neckline";
 	public String _4_news_from_date="news_from_date";
 	public String _4_news_to_date="news_to_date";
 	public String _4_old_id="old_id";
 	public String _4_options_container="options_container";
 	public String _4_page_layout="page_layout";
 	public String _4_price="price";
 	public String _4_price_type="price_type";
 	public String _4_price_view="price_view";
 	public String _4_recurring_profile="recurring_profile";
 	public String _4_required_options="required_options";
 	public String _4_samples_title="samples_title";
 	public String _4_season="season";
 	public String _4_shipment_type="shipment_type";
 	public String _4_short_description="short_description";
 	public String _4_sillouette="sillouette";
 	public String _4_sku="sku";
 	public String _4_sku_type="sku_type";
 	public String _4_sleeve_length="sleeve_length";
 	public String _4_sleeve_style="sleeve_style";
 	public String _4_small_image="small_image";
 	public String _4_small_image_label="small_image_label";
 	public String _4_special_from_date="special_from_date";
 	public String _4_special_occasion_dresses="special_occasion_dresses";
 	public String _4_special_price="special_price";
 	public String _4_special_to_date="special_to_date";
 	public String _4_status="status";
 	public String _4_style="style";
 	public String _4_tax_class_id="tax_class_id";
 	public String _4_thumbnail="thumbnail";
 	public String _4_thumbnail_label="thumbnail_label";
 	public String _4_tier_price="tier_price";
 	public String _4_train="train";
 	public String _4_updated_at="updated_at";
 	public String _4_url_key="url_key";
 	public String _4_url_path="url_path";
 	public String _4_venues="venues";
 	public String _4_visibility="visibility";
 	public String _4_waistline="waistline";
 	public String _4_wedding_dresses="wedding_dresses";
 	public String _4_weight="weight";
 	public String _4_weight_type="weight_type";
 	public String _9_code="code";
 	public String _9_default_mask0="default_mask0";
 	public String _9_display="display";
 	public String _9_is_enabled="is_enabled";
 	public String _9_is_enabled_in_search="is_enabled_in_search";
 	public String _9_name="name";
 	public String _9_position="position";

}
